// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZ2Ij-lKn0ZKspAnwcfi3RODGWMv3G5A',
    appId: '1:287905481797:web:9540a6601d67d69d53cf2c',
    messagingSenderId: '287905481797',
    projectId: 'app-vendas-ee228',
    authDomain: 'app-vendas-ee228.firebaseapp.com',
    storageBucket: 'app-vendas-ee228.firebasestorage.app',
    measurementId: 'G-DBQBS8X6K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4eQNPEK3zd1qdy-xlOveJoeBEzdMHMD8',
    appId: '1:287905481797:android:e4788892988b7a6a53cf2c',
    messagingSenderId: '287905481797',
    projectId: 'app-vendas-ee228',
    storageBucket: 'app-vendas-ee228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjH5Z1X2lCWOcJUg3WGW9bJrRru74r8Q',
    appId: '1:287905481797:ios:00175cef944fd3e153cf2c',
    messagingSenderId: '287905481797',
    projectId: 'app-vendas-ee228',
    storageBucket: 'app-vendas-ee228.firebasestorage.app',
    iosBundleId: 'com.example.appVendas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjH5Z1X2lCWOcJUg3WGW9bJrRru74r8Q',
    appId: '1:287905481797:ios:00175cef944fd3e153cf2c',
    messagingSenderId: '287905481797',
    projectId: 'app-vendas-ee228',
    storageBucket: 'app-vendas-ee228.firebasestorage.app',
    iosBundleId: 'com.example.appVendas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZ2Ij-lKn0ZKspAnwcfi3RODGWMv3G5A',
    appId: '1:287905481797:web:a4811686e6bebc8b53cf2c',
    messagingSenderId: '287905481797',
    projectId: 'app-vendas-ee228',
    authDomain: 'app-vendas-ee228.firebaseapp.com',
    storageBucket: 'app-vendas-ee228.firebasestorage.app',
    measurementId: 'G-YVV2HM2ZW1',
  );
}
